### ISSUE TITLE
How can I disable auto-complete-mode?

### ISSUE THREAD

**Issue by caisah** [aki2o/emacs-tss#26]
Thanks for all the work you put in `tss`. I have a small problem though. I was trying to programmatically disable `auto-complete-mode` in the `typescript-mode-hook` but couldn't. 
How can I achieve this?

**Comment by aki2o** [comment]
Hi, @caisah 
Try to configure `'(lambda () (auto-complete-mode 0))` after `tss-config-default` in `typescript-mode-hook`.

**Comment by caisah** [comment]
Thanks it works great. I'm just a noob :flushed:
